[package]
name = "rs"
version = "0.1.0"
authors = ["wasmup <authors>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"              # Random number generators and other randomness functionality.